import type { Metadata } from "next";
import { Noto_Sans_Thai, Noto_Sans } from "next/font/google";
import "./globals.css";

const notoThai = Noto_Sans_Thai({
  subsets: ["thai"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-thai",
  display: "swap",
});

const notoSans = Noto_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-latin",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Next-Redis-Dashboard-App",
  description: "Generated by create next app",
  icons: {
    icon: "/redis.svg",
    shortcut: "/redis.svg",
    apple: "/redis.svg",
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="th" className={`${notoThai.variable} ${notoSans.variable}`}>
      <body className="font-sans">{children}</body>
    </html>
  );
}
